query ActivityDetailsQuery($activityId: Int) {
    Activity(id: $activityId) {
        ...on TextActivity {
            ... TextActivityFragment
            replies {
                ...ReplyFragment
            }
        }
        ...on ListActivity {
            ...ListActivityFragment
            user {
                name
                avatar {
                    medium
                }
            }
            replies {
                ...ReplyFragment
            }
        }
        ... on MessageActivity {
            ...MessageActivityFragment
            replies {
                ...ReplyFragment
            }
        }
    }
}

fragment ReplyFragment on ActivityReply {
    id
    createdAt
    isLiked
    likeCount
    text
    userId
    user {
        name
        avatar {
            medium
        }
    }
}

fragment ListActivityFragment on ListActivity {
    id
    createdAt
    isLiked
    likeCount
    replyCount
    isLocked
    type
    progress
    status
    userId
    user {
        name
        avatar {
            medium
        }
    }
    media {
        id
        title {
            userPreferred
        }
        coverImage {
            medium
        }
    }
}

fragment MessageActivityFragment on MessageActivity {
    id
    createdAt
    isLiked
    likeCount
    replyCount
    isLocked
    message
    messengerId
    messenger {
        name
        avatar {
            medium
        }
    }
}

fragment TextActivityFragment on TextActivity {
    id
    createdAt
    isLiked
    likeCount
    replyCount
    isLocked
    text
    userId
    user {
        name
        avatar {
            medium
        }
    }
}