schema: "./GraphQL/schema/schema.graphql"
documents: "./GraphQL/**/*.graphql"
extensions:
  endpoints:
    AniListAPI:
      url: "https://graphql.anilist.co"
      headers:
        Content-Type: application/json